### ISSUE TITLE
two identical statement

### ISSUE THREAD

**Issue by pppaulpeter** [MakerMeik/Timelapse#2]
Hi,
why there are two identical statement in the convert.sh file?

**_ffmpeg -i /home/pi/Timelapse/vids/timelapse-weather_${today}.avi -c:v copy -an /home/pi/Timelapse/vids/timelapse-weather_${today}.mp4

ffmpeg -i /home/pi/Timelapse/vids/timelapse-weather_${today}.avi -c:v copy -an /home/pi/Timelapse/vids/timelapse-weather_${today}.mp4_**

**Comment by MakerMeik** [comment]
Yes, you are correct. That was a copy-paste error that arose from my file actually running on my server. I have corrected it right away and am closing the issue. Thanks for the tip.
