### ISSUE TITLE
incorrect check for time lapse

### ISSUE THREAD

**Issue by ramanraja** [MakerMeik/Timelapse#4]
In the file CameraWebServer.ino, the line
`previousMillis = currentMillis; `
is inside the double braces; it will never be executed, since the ESP is restarted in the previous line.
Please move it to an `else` block outside of the braces.

**Comment by MakerMeik** [comment]
Hi @ramanraja, 
thanks for the tip. I have fixed the error. In the meantime, however, I would rather advise the "esp32-cam-webserver" project. It runs much more stable than the example project used here and has some additional features.

[<https://github.com/easytarget/esp32-cam-webserver>]
